import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const H = (h: string) => JSON.stringify({ mon: h, tue: h, wed: h, thu: h, fri: h, sat: h, sun: h });
const HWD = (wd: string, sat: string, sun: string) => JSON.stringify({ mon: wd, tue: wd, wed: wd, thu: wd, fri: wd, sat, sun });

async function main() {
  console.log("Seeding...");
  await prisma.tripPlan.deleteMany();
  await prisma.shop.deleteMany();
  await prisma.cluster.deleteMany();

  // ══════════════ CLUSTERS (12) ══════════════
  const clusters = [
    { id: "cluster-harco", name: "Harco Mangga Dua", type: "mall", address: "Jl. Mangga Dua Raya, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1377, longitude: 106.8284, avgVisitMinutes: 25, parkingInfo: "Parkir motor Rp 5.000, mobil Rp 10.000-15.000", bestVisitTime: "Weekday 10:00-14:00" },
    { id: "cluster-mangga-dua-mall", name: "Mangga Dua Mall", type: "mall", address: "Jl. Mangga Dua Raya, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1380, longitude: 106.8290, avgVisitMinutes: 25, parkingInfo: "Basement parking available", bestVisitTime: "Weekday 11:00-15:00" },
    { id: "cluster-itc-fatmawati", name: "ITC Fatmawati", type: "mall", address: "Jl. RS Fatmawati No.39, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2923, longitude: 106.7970, avgVisitMinutes: 30, parkingInfo: "Parkir basement, motor Rp 3.000", bestVisitTime: "Any day 11:00-17:00" },
    { id: "cluster-itc-permata-hijau", name: "Grand ITC Permata Hijau", type: "mall", address: "Jl. Letjen Soepeno, Kebayoran Lama, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2275, longitude: 106.7820, avgVisitMinutes: 30, parkingInfo: "Parkir luas, motor Rp 3.000", bestVisitTime: "Weekday recommended" },
    { id: "cluster-mall-ambassador", name: "Mall Ambassador", type: "mall", address: "Jl. Prof. DR. Satrio, Kuningan, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2270, longitude: 106.8310, avgVisitMinutes: 25, parkingInfo: "Basement parking", bestVisitTime: "Weekday 10:00-16:00" },
    { id: "cluster-roxy", name: "ITC Roxy Mas & Roxy Square", type: "mall", address: "Jl. KH. Hasyim Ashari, Grogol Petamburan, Jakarta Barat", district: "Jakarta Barat", latitude: -6.1670, longitude: 106.8000, avgVisitMinutes: 25, parkingInfo: "Multiple parking areas", bestVisitTime: "Weekday 10:00-15:00" },
    { id: "cluster-tanjung-duren", name: "Tanjung Duren Area", type: "area", address: "Jl. Tanjung Duren Raya, Jakarta Barat", district: "Jakarta Barat", latitude: -6.1750, longitude: 106.7850, avgVisitMinutes: 20, parkingInfo: "Street parking", bestVisitTime: "Any time during business hours" },
    { id: "cluster-kelapa-gading", name: "Kelapa Gading Area", type: "area", address: "Kelapa Gading, Jakarta Utara", district: "Jakarta Utara", latitude: -6.1580, longitude: 106.9050, avgVisitMinutes: 25, parkingInfo: "Mall or street parking", bestVisitTime: "Weekday to avoid traffic" },
    { id: "cluster-bcp", name: "Bekasi Cyber Park", type: "mall", address: "Jl. Ahmad Yani, Bekasi", district: "Bekasi", latitude: -6.2480, longitude: 107.0000, avgVisitMinutes: 25, parkingInfo: "Mall parking", bestVisitTime: "Weekday recommended" },
    { id: "cluster-cempaka-mas", name: "ITC Cempaka Mas", type: "mall", address: "Jl. Letjen Suprapto, Kemayoran, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1660, longitude: 106.8740, avgVisitMinutes: 25, parkingInfo: "Large parking area", bestVisitTime: "Weekday 10:00-16:00" },
    { id: "cluster-jaksel-scattered", name: "Jakarta Selatan (Various)", type: "area", address: "Various locations in South Jakarta", district: "Jakarta Selatan", latitude: -6.2600, longitude: 106.8100, avgVisitMinutes: 30, parkingInfo: "Varies by location", bestVisitTime: "Plan specific routes" },
    { id: "cluster-jakut-scattered", name: "Jakarta Utara (Various)", type: "area", address: "Various locations in North Jakarta", district: "Jakarta Utara", latitude: -6.1400, longitude: 106.8600, avgVisitMinutes: 30, parkingInfo: "Varies by location", bestVisitTime: "Early morning to avoid traffic" },
  ];
  for (const c of clusters) { await prisma.cluster.create({ data: c }); }
  console.log(`${clusters.length} clusters`);

  // ══════════════ TIER S: SURFACE SPECIALISTS (6) ══════════════
  const tierS = [
    { name: "Zapplerepair Indonesia - HQ", address: "Jl. Jembatan 3 Raya Ruko 11J", district: "Jakarta Utara", area: "Pluit/Penjaringan", clusterId: "cluster-jakut-scattered", latitude: -6.1230, longitude: 106.8050, phone: "021-26081043", whatsapp: "087788855868", website: "zapplerepair.com", instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 500, tier: "S", tierReason: "ONLY dedicated Surface specialist in Indonesia. Complete parts inventory for all Surface models. Published Surface-specific pricing. International warranty assistance.", surfaceConfirmed: true, surfaceNotes: "Surface Pro 4/5/6/7, Surface Book, Surface Laptop, Surface Go. LCD Rp 1.8M-2.9M + Rp 600K labor. 9 month warranty.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Surface Motherboard", "Surface Data Recovery", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2900000, laborFee: 600000, warrantyDays: 270, operatingHours: HWD("08:00-20:00", "09:00-18:00", "09:00-18:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface", "MacBook", "Gaming Laptop"]), certifications: null, dataSource: "Document 1,3,4" },
    { name: "Zapplerepair - Roxy Square", address: "Roxy Square Lt. LG Blok B1 No. 1 & 25, Jl. Kyai Tapa No. 1", district: "Jakarta Barat", area: "Grogol Petamburan", clusterId: "cluster-roxy", latitude: -6.1672, longitude: 106.7998, phone: "021-26081043", whatsapp: "087788855868", website: "zapplerepair.com", instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 300, tier: "S", tierReason: "Branch of Zapplerepair - Surface specialist with same capabilities as HQ", surfaceConfirmed: true, surfaceNotes: "Same Surface services as HQ. Convenient mall location.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Surface Motherboard", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2900000, laborFee: 600000, warrantyDays: 270, operatingHours: H("11:00-20:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface", "MacBook", "Gaming Laptop"]), certifications: null, dataSource: "Document 1,3,4" },
    { name: "Zapplerepair - Mampang", address: "Jl. Mampang Prapatan Raya No. 24C", district: "Jakarta Selatan", area: "Mampang Prapatan", clusterId: "cluster-jaksel-scattered", latitude: -6.2510, longitude: 106.8280, phone: "021-26081043", whatsapp: "087788855868", website: "zapplerepair.com", instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 200, tier: "S", tierReason: "Branch of Zapplerepair - Surface specialist, closest to starting point", surfaceConfirmed: true, surfaceNotes: "Same Surface services as HQ. South Jakarta location.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Surface Motherboard", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2900000, laborFee: 600000, warrantyDays: 270, operatingHours: H("08:00-16:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface", "MacBook", "Gaming Laptop"]), certifications: null, dataSource: "Document 1,3,4" },
    { name: "JETSiNDO - Tanjung Duren", address: "Jl. Mangga 5 No. 20B, Tanjung Duren, Kebon Jeruk", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1732, longitude: 106.7820, phone: null, whatsapp: "087883343470", website: "jetsindo.com", instagram: null, instagramFollowers: null, googleRating: 4.9, googleReviews: 350, tier: "S", tierReason: "FASTEST Surface repairs (1-hour confirmed). Owner Johan Tandra has 17 years experience, Apple Certified Technician. Excellent reviews specifically for Surface screen repairs.", surfaceConfirmed: true, surfaceNotes: "1-hour LCD replacement reported. Surface Pro 4 upgrade to Pro 5 LCD available (Rp 3.78M). 90-day warranty.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Windows Laptop", "MacBook"]), lcdPriceMin: 2500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-18:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 17, specializations: JSON.stringify(["Microsoft Surface", "Windows Laptop", "MacBook"]), certifications: "Apple Certified Technician (New York)", dataSource: "Document 3,4" },
    { name: "JETSiNDO - Cilandak", address: "Jl. Terogong Raya No. 52D, Cilandak", district: "Jakarta Selatan", area: "Cilandak", clusterId: "cluster-jaksel-scattered", latitude: -6.2850, longitude: 106.7910, phone: null, whatsapp: "087883343470", website: "jetsindo.com", instagram: null, instagramFollowers: null, googleRating: 4.9, googleReviews: 200, tier: "S", tierReason: "Second branch of JETSiNDO with same Surface expertise", surfaceConfirmed: true, surfaceNotes: "Same capabilities as main branch. South Jakarta coverage.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Windows Laptop", "MacBook"]), lcdPriceMin: 2500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-18:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 17, specializations: JSON.stringify(["Microsoft Surface", "Windows Laptop", "MacBook"]), certifications: "Apple Certified Technician", dataSource: "Document 3,4" },
    { name: "Dr. Gadget", address: "8 branches across Jabodetabek (ITC Fatmawati main)", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2923, longitude: 106.7970, phone: null, whatsapp: null, website: null, instagram: "@docgadget_", instagramFollowers: 76000, googleRating: 4.7, googleReviews: 2000, tier: "S", tierReason: "Explicitly listed as '#1 for Surface' in research. BNSP certified technicians. Original spare parts with warranty for Surface.", surfaceConfirmed: true, surfaceNotes: "Multi-specialty including Microsoft Surface, Gaming Laptops, Nintendo. Door-to-door service available.", services: JSON.stringify(["Microsoft Surface", "Gaming Laptop", "Nintendo", "Apple Devices"]), lcdPriceMin: 2500000, lcdPriceMax: 5000000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 8, specializations: JSON.stringify(["Microsoft Surface", "Gaming Laptop", "Apple", "Nintendo"]), certifications: "BNSP Certified", dataSource: "Document 1,2" },
  ];

  // ══════════════ TIER A: CONFIRMED CAPABLE (5) ══════════════
  const tierA = [
    { name: "ServiceNotebookJakarta", address: "Jl. Adhi Karya, Pintu Air 3 No. 56C, Kedoya Selatan, Kebon Jeruk", district: "Jakarta Barat", area: "Kebon Jeruk", clusterId: "cluster-tanjung-duren", latitude: -6.1680, longitude: 106.7650, phone: null, whatsapp: "082117854186", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 150, tier: "A", tierReason: "LCD Replacement Specialist since 2011 (14+ years). Handles premium brands including Dell XPS, HP Spectre, Asus Zenbook. Confirmed handles Surface-class devices.", surfaceConfirmed: true, surfaceNotes: "Owner clarifies all laptop LCDs use third-party OEM panels. Specializes in cracked, flickering, blank screens.", services: JSON.stringify(["LCD Replacement", "Premium Laptop", "All Brands"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: 300000, warrantyDays: 30, operatingHours: HWD("17:00-19:00", "closed", "closed"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 14, specializations: JSON.stringify(["LCD Replacement", "Premium Laptop"]), certifications: null, dataSource: "Document 3" },
    { name: "Pemmztechie - Cilandak", address: "Jl. H. Nawi Raya No. 9M, Ruko Galeri Niaga, Cilandak", district: "Jakarta Selatan", area: "Cilandak", clusterId: "cluster-jaksel-scattered", latitude: -6.2780, longitude: 106.7950, phone: "021-5697-3669", whatsapp: "085280280100", website: "pemmztechie.id", instagram: "@pemmztechie.id", instagramFollowers: 6541, googleRating: 4.6, googleReviews: 600, tier: "A", tierReason: "First Indonesian Gaming Laptop Store. 10+ years, 100,000+ customers. Handles premium laptops including ROG, Alienware, MSI - similar build complexity to Surface.", surfaceConfirmed: false, surfaceNotes: "Not explicitly confirmed but premium laptop expertise suggests capability. Contact to verify Surface parts availability.", services: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI", "Razer", "Premium Laptop"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-18:00", "10:00-16:00", "10:00-16:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI", "Razer"]), certifications: null, dataSource: "Document 1,2,3" },
    { name: "Pemmztechie - Tanjung Duren HQ", address: "Jl. Tanjung Duren Raya 17A, Blok A11", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1745, longitude: 106.7840, phone: null, whatsapp: "085280280100", website: "pemmztechie.id", instagram: "@pemmztechie.id", instagramFollowers: 6541, googleRating: 4.6, googleReviews: 400, tier: "A", tierReason: "HQ of Pemmztechie - premium laptop specialist. Zet-Zet cleaning service.", surfaceConfirmed: false, surfaceNotes: "Gaming laptop expertise suggests premium device capability.", services: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI", "Cleaning"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: null, warrantyDays: 90, operatingHours: HWD("10:00-18:00", "10:00-16:00", "10:00-16:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Gaming Laptop", "Premium Laptop"]), certifications: null, dataSource: "Document 1,2" },
    { name: "Arisa Computer", address: "Mall Ambassador Lt. 3 No. 45", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2270, longitude: 106.8310, phone: null, whatsapp: "08111041840", website: null, instagram: "@arisacomp", instagramFollowers: 10000, googleRating: 4.7, googleReviews: 300, tier: "A", tierReason: "Premium service - free laptop loaner during repair, free pickup/delivery. Lenovo specialist with premium brand experience.", surfaceConfirmed: false, surfaceNotes: "Premium service level suggests capability for high-end devices. Confirm Surface parts availability.", services: JSON.stringify(["Lenovo", "All Brands", "Premium Service"]), lcdPriceMin: 1500000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Lenovo", "Premium Service"]), certifications: null, dataSource: "Document 2,3" },
    { name: "iRepair Computer - ITC Fatmawati", address: "ITC Fatmawati LD No. 148", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2920, longitude: 106.7968, phone: null, whatsapp: "08176411234", website: "servicelaptoptangerang.com", instagram: "@servicelaptop_tangerang", instagramFollowers: 3000, googleRating: 5.0, googleReviews: 80, tier: "A", tierReason: "Perfect 5.0 rating. Handles all brands + MacBook. Premium device experience suggests Surface capability.", surfaceConfirmed: false, surfaceNotes: "All brands capable with perfect rating. Contact to confirm Surface parts.", services: JSON.stringify(["All Brands", "MacBook", "VGA Chipset", "Data Recovery"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands", "MacBook"]), certifications: null, dataSource: "Document 1,2" },
  ];

  // ══════════════ TIER B: LIKELY CAPABLE (15) ══════════════
  const tierB = [
    { name: "Teknisigo - Tebet", address: "Jl. Tebet Timur Dalam Raya", district: "Jakarta Selatan", area: "Tebet", clusterId: "cluster-jaksel-scattered", latitude: -6.2270, longitude: 106.8520, phone: null, whatsapp: null, website: "teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.8, googleReviews: 1500, tier: "B", tierReason: "Market leader with 244K Instagram followers, 18+ years experience. Handles all brands. Real-time tracking system.", surfaceConfirmed: false, surfaceNotes: "Highest social presence. All brands capable. Verify Surface parts before visiting.", services: JSON.stringify(["All Brands", "LCD", "Battery", "SSD Upgrade", "Hinge Repair"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["All Brands", "Home Service"]), certifications: null, dataSource: "Document 1,2" },
    { name: "Teknisigo - Harco Mangga Dua", address: "Harco Mangga Dua Plaza", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1377, longitude: 106.8284, phone: null, whatsapp: null, website: "teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 800, tier: "B", tierReason: "Branch of Teknisigo in electronics hub. Large parts availability.", surfaceConfirmed: false, surfaceNotes: "Access to wholesale parts market in Mangga Dua.", services: JSON.stringify(["All Brands", "LCD", "Battery", "SSD Upgrade"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,2" },
    { name: "Sodagar Komputer - Rawamangun", address: "Jl. Sunan Giri No. 5, Rawamangun", district: "Jakarta Timur", area: "Rawamangun", clusterId: null, latitude: -6.1930, longitude: 106.8790, phone: null, whatsapp: "082123790480", website: "sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 500, tier: "B", tierReason: "Longest operating (since 2002, 23 years). Authorized for Lenovo, HP, Asus, Acer. 10+ branches. 3000+ total Google reviews.", surfaceConfirmed: false, surfaceNotes: "Extensive experience with authorized brand service. May handle Surface as premium device.", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer", "Axioo"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), certifications: "Authorized Service Partner", dataSource: "Document 1,2" },
    { name: "Sodagar Komputer - Ampera", address: "Jl. Ampera Raya No. 4", district: "Jakarta Selatan", area: "Ampera", clusterId: "cluster-jaksel-scattered", latitude: -6.2660, longitude: 106.8240, phone: null, whatsapp: "082123790480", website: "sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 400, tier: "B", tierReason: "Sodagar branch in South Jakarta. Same capabilities.", surfaceConfirmed: false, surfaceNotes: "South Jakarta coverage.", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), certifications: "Authorized Service Partner", dataSource: "Document 1" },
    { name: "Rimas Laptop Jakarta - Tanjung Duren", address: "Jl. Tanjung Duren Raya", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1748, longitude: 106.7835, phone: "7635989777", whatsapp: null, website: null, instagram: "@rimaslaptopjakarta", instagramFollowers: 68000, googleRating: 4.7, googleReviews: 500, tier: "B", tierReason: "68K Instagram followers. Home service available. 7+ branches in Jabodetabek.", surfaceConfirmed: false, surfaceNotes: "General service with massive social presence. Home service convenient.", services: JSON.stringify(["All Brands", "Buy/Sell", "Trade-in", "Home Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-22:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["All Brands", "Buy/Sell"]), certifications: null, dataSource: "Document 1,2" },
    { name: "Rimas Laptop - Kelapa Gading", address: "Jl. Boulevard Raya Blok LA 6 No. 7, opposite Summarecon Mall", district: "Jakarta Utara", area: "Kelapa Gading", clusterId: "cluster-kelapa-gading", latitude: -6.1580, longitude: 106.9050, phone: "7635905905", whatsapp: "081234565741", website: null, instagram: "@rimaslaptop.kelapagading", instagramFollowers: 64000, googleRating: 4.8, googleReviews: 600, tier: "B", tierReason: "Highest rated Rimas branch. Extended hours until 10PM.", surfaceConfirmed: false, surfaceNotes: "Customer review: 'Service laptop ganti LCD disini sangat memuaskan.'", services: JSON.stringify(["All Brands", "LCD", "Home Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-22:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,3" },
    { name: "R Komputer", address: "Grand ITC Permata Hijau Lt. 3 Blok D2 No. 03", district: "Jakarta Selatan", area: "Kebayoran Lama", clusterId: "cluster-itc-permata-hijau", latitude: -6.2275, longitude: 106.7820, phone: null, whatsapp: "081292502305", website: null, instagram: "@rizkalaptop", instagramFollowers: null, googleRating: 5.0, googleReviews: 70, tier: "B", tierReason: "Perfect 5.0 rating since 2011. Fast service, honest technicians, warranty included.", surfaceConfirmed: false, surfaceNotes: "Premium location in ITC Permata Hijau. All brands capable.", services: JSON.stringify(["All Brands", "Fast Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 14, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 2,3" },
    { name: "Quick Service BCP", address: "Mall Bekasi Cyber Park Lt. 1, Blok B2, No. 17", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2480, longitude: 107.0000, phone: null, whatsapp: "085107771771", website: null, instagram: "@quick_service_laptop", instagramFollowers: null, googleRating: 4.9, googleReviews: 469, tier: "B", tierReason: "Highest Bekasi rating 4.9/5 with 469 reviews. All brands. 1-month warranty.", surfaceConfirmed: false, surfaceNotes: "Best in Bekasi. All brands capable.", services: JSON.stringify(["All Brands", "LCD", "Keyboard", "Battery", "Hinge", "SSD Upgrade"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,2" },
    { name: "ZetZet.id", address: "Tanjung Duren Raya 17A, Blok A11 Kav 16", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1746, longitude: 106.7838, phone: null, whatsapp: "085776938938", website: null, instagram: "@mr.zetzet", instagramFollowers: 4700, googleRating: 4.7, googleReviews: 300, tier: "B", tierReason: "10+ years experience. All LCD types (IPS, TN, VA). Part sourcing assistance.", surfaceConfirmed: false, surfaceNotes: "Helps source quality spare parts matching original specs.", services: JSON.stringify(["LCD", "Cleaning", "Thermal Paste", "All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-18:00", "10:00-16:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["LCD", "Cleaning"]), certifications: null, dataSource: "Document 2,3" },
    { name: "Unicomputer", address: "Mall Ambassador Lt. 2 Jembatan 2 No. 56", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2268, longitude: 106.8308, phone: null, whatsapp: "08112626146", website: null, instagram: "@unicomputer.id", instagramFollowers: null, googleRating: 4.6, googleReviews: 100, tier: "B", tierReason: "On-site corporate service available. MacBook + PC capable.", surfaceConfirmed: false, surfaceNotes: "Corporate service suggests premium device experience.", services: JSON.stringify(["MacBook", "PC", "Corporate Service"]), lcdPriceMin: 1000000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "closed"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Corporate Service"]), certifications: null, dataSource: "Document 1,3" },
    { name: "Ziro Laptop", address: "Mall Ambassador Lt. 3 Jembatan 2 No. 47", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2269, longitude: 106.8309, phone: null, whatsapp: "081361706175", website: null, instagram: "@zirolaptop", instagramFollowers: 987, googleRating: 4.7, googleReviews: 150, tier: "B", tierReason: "7+ years experience. Apple + general capable.", surfaceConfirmed: false, surfaceNotes: "Premium device experience from Apple service.", services: JSON.stringify(["Apple", "All Brands"]), lcdPriceMin: 1000000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 7, specializations: JSON.stringify(["Apple", "All Brands"]), certifications: null, dataSource: "Document 1,3" },
    { name: "Dokter Laptop", address: "Mall Ambassador Lt. 3 No. 47", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2267, longitude: 106.8307, phone: null, whatsapp: "081281010197", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 350, tier: "B", tierReason: "Detailed diagnosis. Strategic business district location.", surfaceConfirmed: false, surfaceNotes: "All brands capable.", services: JSON.stringify(["All Brands", "Detailed Diagnosis"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,2" },
    { name: "Valdis Computer", address: "Kelapa Gading", district: "Jakarta Utara", area: "Kelapa Gading", clusterId: "cluster-kelapa-gading", latitude: -6.1585, longitude: 106.9045, phone: "+622145850242", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 400, tier: "B", tierReason: "22+ years operation since 2001. Gaming + general laptop. Professional service.", surfaceConfirmed: false, surfaceNotes: "Long experience suggests premium device capability.", services: JSON.stringify(["Gaming", "All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 24, specializations: JSON.stringify(["Gaming", "All Brands"]), certifications: null, dataSource: "Document 2" },
    { name: "Bengkel Laptop (N-AISY)", address: "Harco Mangga Dua Lt. Dasar No. 91 (hook)", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1376, longitude: 106.8282, phone: null, whatsapp: "081218534516", website: null, instagram: "@bengkellaptop_", instagramFollowers: 4000, googleRating: 4.7, googleReviews: 400, tier: "B", tierReason: "Since 2004 (20+ years). All brands. Harco location for parts access.", surfaceConfirmed: false, surfaceNotes: "Long-established with parts access in Mangga Dua.", services: JSON.stringify(["All Brands", "LCD", "Battery", "Keyboard", "RAM", "SSD"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: 100000, warrantyDays: 30, operatingHours: HWD("09:30-18:30", "09:30-18:30", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 21, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,2,3" },
    { name: "TeknisiGo (Home Service)", address: "Coverage: All Jabodetabek", district: "Jabodetabek", area: "Mobile Service", clusterId: null, latitude: -6.2000, longitude: 106.8166, phone: null, whatsapp: "085780864001", website: "teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 500, tier: "B", tierReason: "Fastest home service. 18+ years. Starting Rp 50,000 visit fee.", surfaceConfirmed: false, surfaceNotes: "Note: Touchscreen/ultrabook excluded from promotional pricing. Confirm Surface rates.", services: JSON.stringify(["Home Service", "All Brands", "Minor Repairs"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: 50000, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["Home Service"]), certifications: null, dataSource: "Document 1,3" },
  ];

  // ══════════════ TIER C: GENERAL REPAIR (19) ══════════════
  const tierC = [
    { name: "Duo Laptop", address: "Harco Mangga Dua Plaza, Blok B Lt. Dasar No. 11", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1378, longitude: 106.8286, phone: null, whatsapp: "081211680089", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 200, tier: "C", tierReason: "Chip-level service specialist. Motherboard repair. Free consultation.", surfaceConfirmed: false, surfaceNotes: "Motherboard expertise may help with complex Surface issues.", services: JSON.stringify(["Motherboard", "Chip-level", "Reballing"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "11:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Motherboard", "Chip-level"]), certifications: null, dataSource: "Document 1,3" },
    { name: "JayaSakti Notebook", address: "Harco Mangga Dua Plaza, Lt. Dasar Blok A No. 94", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1375, longitude: 106.8280, phone: "021-6120630", whatsapp: "081211680089", website: null, instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 150, tier: "C", tierReason: "All brands. Parts replacement specialist.", surfaceConfirmed: false, surfaceNotes: "General repair in parts hub.", services: JSON.stringify(["All Brands", "Parts Replacement"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-20:00", "10:00-18:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,3" },
    { name: "FIXPRO Service", address: "Mall Mangga Dua Lt. 5 Blok K No. 4", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1381, longitude: 106.8292, phone: null, whatsapp: "081212962827", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 100, tier: "C", tierReason: "Hardware specialist. Budget pricing.", surfaceConfirmed: false, surfaceNotes: "Hardware focus may help with Surface issues.", services: JSON.stringify(["Hardware", "All Brands"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: 50000, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Hardware"]), certifications: null, dataSource: "Document 1" },
    { name: "Hariez Central Service", address: "Mall Mangga2 Lt. 5 Block C59-60", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1382, longitude: 106.8294, phone: null, whatsapp: "081313006700", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 100, tier: "C", tierReason: "Honest diagnostics reputation. 'Anti gagal' service.", surfaceConfirmed: false, surfaceNotes: "Known for honest assessments.", services: JSON.stringify(["All Brands", "Honest Diagnosis"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Honest Diagnosis"]), certifications: null, dataSource: "Document 1" },
    { name: "Irepair ABA - Lebak Bulus", address: "Jl. Lebak Bulus Raya No. 5 (depan masjid PTIQ)", district: "Jakarta Selatan", area: "Lebak Bulus", clusterId: "cluster-jaksel-scattered", latitude: -6.2890, longitude: 106.7780, phone: null, whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 80, tier: "C", tierReason: "All brands. Free checkup for loyal customers.", surfaceConfirmed: false, surfaceNotes: "General all-brand service.", services: JSON.stringify(["All Brands", "LCD", "Battery", "Keyboard", "Mainboard"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1,3" },
    { name: "Laptop Heal", address: "Jl. Tegal Parang Selatan I No. 15, Mampang", district: "Jakarta Selatan", area: "Mampang", clusterId: "cluster-jaksel-scattered", latitude: -6.2490, longitude: 106.8340, phone: null, whatsapp: "085729116000", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 80, tier: "C", tierReason: "Troubleshooting specialist. Budget-friendly. 'Konsultan komputer'.", surfaceConfirmed: false, surfaceNotes: "Budget option for troubleshooting.", services: JSON.stringify(["Troubleshooting", "Budget Service"]), lcdPriceMin: 500000, lcdPriceMax: 1500000, laborFee: 50000, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Troubleshooting"]), certifications: null, dataSource: "Document 1" },
    { name: "Aries Komputer", address: "Jl. Basuki gang pulau harapan No. 5, Cilangkap, Cipayung", district: "Jakarta Timur", area: "Cipayung", clusterId: null, latitude: -6.3180, longitude: 106.9120, phone: null, whatsapp: "087878004197", website: null, instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 100, tier: "C", tierReason: "Owner-operated personal service. Honest pricing. Extended hours 8AM-9PM.", surfaceConfirmed: false, surfaceNotes: "Personal attention, flexible on parts sourcing.", services: JSON.stringify(["All Brands", "Personal Service"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Personal Service"]), certifications: null, dataSource: "Document 1,3" },
    { name: "Sentral Service BCP", address: "Bekasi Cyber Park Lt. 1 Blok A11 No. 22", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2482, longitude: 107.0002, phone: null, whatsapp: "081977771800", website: null, instagram: "@sentralservice_bcp", instagramFollowers: 1400, googleRating: 4.7, googleReviews: 200, tier: "C", tierReason: "HP Official Partner. ROG specialist.", surfaceConfirmed: false, surfaceNotes: "Official partner status suggests quality.", services: JSON.stringify(["HP", "ROG", "All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["HP", "ROG"]), certifications: "HP Official Partner", dataSource: "Document 1,2" },
    { name: "Juniar Computer", address: "Bekasi Cyber Park Lt. 1 Blok A3 No. 8", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2478, longitude: 107.0001, phone: null, whatsapp: "082216242081", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 150, tier: "C", tierReason: "General + projector. Parts in stock.", surfaceConfirmed: false, surfaceNotes: "Good parts availability.", services: JSON.stringify(["All Brands", "Projector"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1" },
    { name: "Don Duan Computer", address: "Bekasi Cyber Park Blok A11", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2481, longitude: 107.0003, phone: null, whatsapp: "082110919414", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 100, tier: "C", tierReason: "Parts in stock. General service.", surfaceConfirmed: false, surfaceNotes: "Parts availability in BCP cluster.", services: JSON.stringify(["All Brands", "Parts"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 1" },
    { name: "Chintya Computer", address: "Jl. Cut Mutia 11, Bekasi Timur", district: "Bekasi", area: "Bekasi Timur", clusterId: null, latitude: -6.2400, longitude: 107.0150, phone: null, whatsapp: "081282872518", website: null, instagram: null, instagramFollowers: null, googleRating: 5.0, googleReviews: 80, tier: "C", tierReason: "Perfect 5.0 rating. Very affordable.", surfaceConfirmed: false, surfaceNotes: "Budget option with excellent reviews.", services: JSON.stringify(["All Brands", "Budget Service"]), lcdPriceMin: 500000, lcdPriceMax: 1500000, laborFee: 50000, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Budget Service"]), certifications: null, dataSource: "Document 1,2" },
    { name: "FixingMac (also Windows)", address: "Grand ITC Permata Hijau Lt. 3 Blok D15 No. 1-2", district: "Jakarta Selatan", area: "Kebayoran Lama", clusterId: "cluster-itc-permata-hijau", latitude: -6.2276, longitude: 106.7822, phone: null, whatsapp: "087787996606", website: null, instagram: "@fixingmac_id", instagramFollowers: 679, googleRating: 4.7, googleReviews: 150, tier: "C", tierReason: "8+ years. MacBook + Windows (Asus, Acer, Lenovo). 2 branches.", surfaceConfirmed: false, surfaceNotes: "Windows laptop capable alongside MacBook.", services: JSON.stringify(["MacBook", "Windows Laptop", "iPhone"]), lcdPriceMin: 1000000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 8, specializations: JSON.stringify(["MacBook", "Windows"]), certifications: null, dataSource: "Document 2,3" },
    { name: "Service HP Roxy Mas", address: "ITC Roxy Mas (3 locations)", district: "Jakarta Barat", area: "Grogol Petamburan", clusterId: "cluster-roxy", latitude: -6.1668, longitude: 106.7996, phone: null, whatsapp: "087869969987", website: null, instagram: "@servicehproxymas", instagramFollowers: 28000, googleRating: 4.7, googleReviews: 500, tier: "C", tierReason: "28K followers. IC repair specialist. 3 Roxy locations.", surfaceConfirmed: false, surfaceNotes: "IC repair expertise may help with complex issues.", services: JSON.stringify(["IC Repair", "All Brands"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["IC Repair"]), certifications: null, dataSource: "Document 2" },
    { name: "Stabiliskom (Home Service Only)", address: "Coverage: Jakarta Barat, Jakarta Selatan, Tangerang", district: "Jabodetabek", area: "Mobile Service", clusterId: null, latitude: -6.2100, longitude: 106.7800, phone: null, whatsapp: "085162816201", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 100, tier: "C", tierReason: "2-hour response time. BIOS/motherboard specialist. Video call diagnosis.", surfaceConfirmed: false, surfaceNotes: "Does not accept walk-ins. Home service only.", services: JSON.stringify(["BIOS", "Motherboard", "Home Service Only"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-20:00", "09:00-18:00", "09:00-18:00"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["BIOS", "Motherboard"]), certifications: null, dataSource: "Document 3" },
    { name: "GMM Komputer", address: "Jl. Tanamas No. 14A, Kapuk, Cengkareng", district: "Jakarta Barat", area: "Cengkareng", clusterId: null, latitude: -6.1280, longitude: 106.7350, phone: null, whatsapp: "081316009353", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 80, tier: "C", tierReason: "Home service Rp 250K includes transport. 1 year spare part warranty. 'If we can't fix, you don't pay'.", surfaceConfirmed: false, surfaceNotes: "Good warranty policy.", services: JSON.stringify(["Home Service", "All Brands"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: 250000, warrantyDays: 365, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Home Service"]), certifications: null, dataSource: "Document 3" },
    { name: "ITHelpDesk Indonesia", address: "CITI HUB - HARTON TOWER Lt. 3, Jl. Boulevard Artha Gading, Kelapa Gading Barat", district: "Jakarta Utara", area: "Kelapa Gading", clusterId: "cluster-kelapa-gading", latitude: -6.1520, longitude: 106.8920, phone: "021-24520565", whatsapp: "08978555777", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 100, tier: "C", tierReason: "Professional/corporate focused. 10+ years. Home visits all Jakarta.", surfaceConfirmed: false, surfaceNotes: "Corporate experience suggests premium device capability.", services: JSON.stringify(["Corporate Service", "Home Service", "All Brands"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-15:00", "closed"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Corporate Service"]), certifications: null, dataSource: "Document 3" },
    { name: "Klinik PC", address: "Jl. Raya Condet No. 25, Balekambang, Kramat Jati", district: "Jakarta Timur", area: "Kramat Jati", clusterId: null, latitude: -6.2750, longitude: 106.8650, phone: null, whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 80, tier: "C", tierReason: "3+ years. Can wait on-site. Loyal customer base.", surfaceConfirmed: false, surfaceNotes: "Smaller operation with personal service.", services: JSON.stringify(["All Brands", "On-site Waiting"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 3, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 3" },
    { name: "Barseyna Komputer", address: "Jl. Enim 2 No. 62, Sungai Bambu, Tanjung Priok", district: "Jakarta Utara", area: "Tanjung Priok", clusterId: null, latitude: -6.1320, longitude: 106.8680, phone: null, whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 50, tier: "C", tierReason: "Fast response. Budget-friendly.", surfaceConfirmed: false, surfaceNotes: "Quick consultation.", services: JSON.stringify(["All Brands", "Budget Service"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Budget Service"]), certifications: null, dataSource: "Document 3" },
    { name: "JakartaNotebook Service Center", address: "Jl. Green Ville Raya Blok Y No. 15A-15C, Duri Kepa, Kebon Jeruk", district: "Jakarta Barat", area: "Kebon Jeruk", clusterId: null, latitude: -6.1620, longitude: 106.7720, phone: null, whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 100, tier: "C", tierReason: "Established retailer. Walk-in service.", surfaceConfirmed: false, surfaceNotes: "Well-known Jakarta computer retailer.", services: JSON.stringify(["All Brands", "Walk-in"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-16:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "Document 3" },
  ];

  const allShops = [...tierS, ...tierA, ...tierB, ...tierC];
  for (const s of allShops) { await prisma.shop.create({ data: s }); }
  console.log(`${allShops.length} shops (S:${tierS.length} A:${tierA.length} B:${tierB.length} C:${tierC.length})`);
  console.log("Done!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
