import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  await prisma.tripPlan.deleteMany();
  await prisma.shop.deleteMany();
  await prisma.cluster.deleteMany();

  // Clusters
  const clusters = [
    {
      id: "cluster-jaksel",
      name: "Jakarta Selatan Area",
      type: "area",
      address: "Various locations, Jakarta Selatan",
      district: "Jakarta Selatan",
      latitude: -6.26,
      longitude: 106.81,
      avgVisitMinutes: 30,
      parkingInfo: "Varies by location",
      bestVisitTime: "Weekday 10:00-16:00",
    },
    {
      id: "cluster-jakbar",
      name: "Jakarta Barat Area",
      type: "area",
      address: "Various locations, Jakarta Barat",
      district: "Jakarta Barat",
      latitude: -6.17,
      longitude: 106.78,
      avgVisitMinutes: 25,
      parkingInfo: "Street parking",
      bestVisitTime: "Any time",
    },
    {
      id: "cluster-jakpus",
      name: "Mangga Dua Mall",
      type: "mall",
      address: "Jl. Mangga Dua Raya, Jakarta Pusat",
      district: "Jakarta Pusat",
      latitude: -6.138,
      longitude: 106.829,
      avgVisitMinutes: 25,
      parkingInfo: "Basement parking available",
      bestVisitTime: "Weekday 11:00-15:00",
    },
  ];

  for (const c of clusters) {
    await prisma.cluster.create({ data: c });
  }
  console.log(`Created ${clusters.length} clusters`);

  // Shops
  const shops = [
    // === TIER S ===
    {
      name: "Zapplerepair Indonesia",
      address: "Jl. Mampang Prapatan Raya No. 24C",
      district: "Jakarta Selatan",
      area: "Mampang Prapatan",
      clusterId: "cluster-jaksel",
      latitude: -6.251,
      longitude: 106.828,
      phone: "021-26081043",
      whatsapp: "087788855868",
      website: "zapplerepair.com",
      instagram: null,
      instagramFollowers: null,
      googleRating: 4.8,
      googleReviews: 500,
      tier: "S",
      tierReason:
        "ONLY dedicated Surface specialist in Indonesia. Complete parts inventory for all Surface models.",
      surfaceConfirmed: true,
      surfaceNotes:
        "Surface Pro 4/5/6/7, Surface Book, Surface Laptop, Surface Go. LCD Rp 1.8M-2.9M + Rp 600K labor. 9 month warranty.",
      services: JSON.stringify(["Surface LCD", "Surface Battery", "Surface Motherboard", "MacBook", "Gaming Laptop"]),
      lcdPriceMin: 1800000,
      lcdPriceMax: 2900000,
      laborFee: 600000,
      warrantyDays: 270,
      operatingHours: JSON.stringify({ mon: "08:00-20:00", tue: "08:00-20:00", wed: "08:00-20:00", thu: "08:00-20:00", fri: "08:00-20:00", sat: "09:00-18:00", sun: "09:00-18:00" }),
      hasHomeService: false,
      hasPickupDelivery: true,
      yearsInBusiness: 10,
      specializations: JSON.stringify(["Microsoft Surface", "MacBook"]),
      certifications: null,
      dataSource: "Document 1,3,4",
    },
    {
      name: "JETSiNDO",
      address: "Jl. Mangga 5 No. 20B, Tanjung Duren",
      district: "Jakarta Barat",
      area: "Tanjung Duren",
      clusterId: "cluster-jakbar",
      latitude: -6.1732,
      longitude: 106.782,
      phone: null,
      whatsapp: "087883343470",
      website: "jetsindo.com",
      instagram: null,
      instagramFollowers: null,
      googleRating: 4.9,
      googleReviews: 350,
      tier: "S",
      tierReason:
        "FASTEST Surface repairs (1-hour confirmed). Owner has 17 years experience, Apple Certified Technician.",
      surfaceConfirmed: true,
      surfaceNotes: "1-hour LCD replacement. Surface Pro 4 upgrade to Pro 5 LCD available (Rp 3.78M). 90-day warranty.",
      services: JSON.stringify(["Surface LCD", "Surface Battery", "Windows Laptop", "MacBook"]),
      lcdPriceMin: 2500000,
      lcdPriceMax: 4000000,
      laborFee: null,
      warrantyDays: 90,
      operatingHours: JSON.stringify({ mon: "10:00-18:00", tue: "10:00-18:00", wed: "10:00-18:00", thu: "10:00-18:00", fri: "10:00-18:00", sat: "10:00-18:00", sun: "10:00-18:00" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: 17,
      specializations: JSON.stringify(["Microsoft Surface", "MacBook"]),
      certifications: "Apple Certified Technician (New York)",
      dataSource: "Document 3,4",
    },
    {
      name: "Dr. Gadget",
      address: "ITC Fatmawati, Jakarta Selatan",
      district: "Jakarta Selatan",
      area: "Fatmawati",
      clusterId: "cluster-jaksel",
      latitude: -6.2923,
      longitude: 106.797,
      phone: null,
      whatsapp: null,
      website: null,
      instagram: "@docgadget_",
      instagramFollowers: 76000,
      googleRating: 4.7,
      googleReviews: 2000,
      tier: "S",
      tierReason:
        "Explicitly listed as #1 for Surface in research. BNSP certified technicians. Original spare parts.",
      surfaceConfirmed: true,
      surfaceNotes: "Multi-specialty including Microsoft Surface, Gaming Laptops, Nintendo.",
      services: JSON.stringify(["Microsoft Surface", "Gaming Laptop", "Nintendo", "Apple Devices"]),
      lcdPriceMin: 2500000,
      lcdPriceMax: 5000000,
      laborFee: null,
      warrantyDays: 90,
      operatingHours: JSON.stringify({ mon: "10:00-20:00", tue: "10:00-20:00", wed: "10:00-20:00", thu: "10:00-20:00", fri: "10:00-20:00", sat: "10:00-20:00", sun: "10:00-20:00" }),
      hasHomeService: true,
      hasPickupDelivery: true,
      yearsInBusiness: 8,
      specializations: JSON.stringify(["Microsoft Surface", "Gaming Laptop", "Apple"]),
      certifications: "BNSP Certified",
      dataSource: "Document 1,2",
    },

    // === TIER A ===
    {
      name: "Pemmztechie",
      address: "Jl. Tanjung Duren Raya 17A, Blok A11",
      district: "Jakarta Barat",
      area: "Tanjung Duren",
      clusterId: "cluster-jakbar",
      latitude: -6.1745,
      longitude: 106.784,
      phone: null,
      whatsapp: "085280280100",
      website: "pemmztechie.id",
      instagram: "@pemmztechie.id",
      instagramFollowers: 6541,
      googleRating: 4.6,
      googleReviews: 400,
      tier: "A",
      tierReason:
        "First Indonesian Gaming Laptop Store. 10+ years, 100,000+ customers. Handles premium laptops.",
      surfaceConfirmed: false,
      surfaceNotes: "Gaming laptop expertise suggests premium device capability.",
      services: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI", "Cleaning"]),
      lcdPriceMin: 1300000,
      lcdPriceMax: 3500000,
      laborFee: null,
      warrantyDays: 90,
      operatingHours: JSON.stringify({ mon: "10:00-18:00", tue: "10:00-18:00", wed: "10:00-18:00", thu: "10:00-18:00", fri: "10:00-18:00", sat: "10:00-16:00", sun: "10:00-16:00" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: 10,
      specializations: JSON.stringify(["Gaming Laptop", "Premium Laptop"]),
      certifications: null,
      dataSource: "Document 1,2",
    },
    {
      name: "Arisa Computer",
      address: "Mall Ambassador Lt. 3 No. 45",
      district: "Jakarta Selatan",
      area: "Kuningan",
      clusterId: "cluster-jaksel",
      latitude: -6.227,
      longitude: 106.831,
      phone: null,
      whatsapp: "08111041840",
      website: null,
      instagram: "@arisacomp",
      instagramFollowers: 10000,
      googleRating: 4.7,
      googleReviews: 300,
      tier: "A",
      tierReason:
        "Premium service - free laptop loaner during repair, free pickup/delivery.",
      surfaceConfirmed: false,
      surfaceNotes: "Premium service level suggests capability for high-end devices.",
      services: JSON.stringify(["Lenovo", "All Brands", "Premium Service"]),
      lcdPriceMin: 1500000,
      lcdPriceMax: 3000000,
      laborFee: null,
      warrantyDays: 30,
      operatingHours: JSON.stringify({ mon: "10:00-20:00", tue: "10:00-20:00", wed: "10:00-20:00", thu: "10:00-20:00", fri: "10:00-20:00", sat: "10:00-20:00", sun: "10:00-20:00" }),
      hasHomeService: false,
      hasPickupDelivery: true,
      yearsInBusiness: null,
      specializations: JSON.stringify(["Lenovo", "Premium Service"]),
      certifications: null,
      dataSource: "Document 2,3",
    },
    {
      name: "iRepair Computer",
      address: "ITC Fatmawati LD No. 148",
      district: "Jakarta Selatan",
      area: "Fatmawati",
      clusterId: "cluster-jaksel",
      latitude: -6.292,
      longitude: 106.7968,
      phone: null,
      whatsapp: "08176411234",
      website: "servicelaptoptangerang.com",
      instagram: "@servicelaptop_tangerang",
      instagramFollowers: 3000,
      googleRating: 5.0,
      googleReviews: 80,
      tier: "A",
      tierReason: "Perfect 5.0 rating. Handles all brands + MacBook.",
      surfaceConfirmed: false,
      surfaceNotes: "All brands capable with perfect rating. Contact to confirm Surface parts.",
      services: JSON.stringify(["All Brands", "MacBook", "VGA Chipset", "Data Recovery"]),
      lcdPriceMin: 800000,
      lcdPriceMax: 2500000,
      laborFee: null,
      warrantyDays: 30,
      operatingHours: JSON.stringify({ mon: "10:00-20:00", tue: "10:00-20:00", wed: "10:00-20:00", thu: "10:00-20:00", fri: "10:00-20:00", sat: "10:00-20:00", sun: "10:00-20:00" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: null,
      specializations: JSON.stringify(["All Brands", "MacBook"]),
      certifications: null,
      dataSource: "Document 1,2",
    },

    // === TIER B ===
    {
      name: "Teknisigo",
      address: "Jl. Tebet Timur Dalam Raya",
      district: "Jakarta Selatan",
      area: "Tebet",
      clusterId: "cluster-jaksel",
      latitude: -6.227,
      longitude: 106.852,
      phone: null,
      whatsapp: null,
      website: "teknisigo.com",
      instagram: "@teknisigo_id",
      instagramFollowers: 244000,
      googleRating: 4.8,
      googleReviews: 1500,
      tier: "B",
      tierReason: "Market leader with 244K followers, 18+ years experience. All brands. Real-time tracking.",
      surfaceConfirmed: false,
      surfaceNotes: "Highest social presence. All brands capable. Verify Surface parts before visiting.",
      services: JSON.stringify(["All Brands", "LCD", "Battery", "SSD Upgrade", "Hinge Repair"]),
      lcdPriceMin: 800000,
      lcdPriceMax: 2500000,
      laborFee: 150000,
      warrantyDays: 90,
      operatingHours: JSON.stringify({ mon: "10:00-20:00", tue: "10:00-20:00", wed: "10:00-20:00", thu: "10:00-20:00", fri: "10:00-20:00", sat: "10:00-20:00", sun: "10:00-20:00" }),
      hasHomeService: true,
      hasPickupDelivery: true,
      yearsInBusiness: 18,
      specializations: JSON.stringify(["All Brands", "Home Service"]),
      certifications: null,
      dataSource: "Document 1,2",
    },
    {
      name: "Bengkel Laptop (N-AISY)",
      address: "Harco Mangga Dua Lt. Dasar No. 91",
      district: "Jakarta Pusat",
      area: "Mangga Dua",
      clusterId: "cluster-jakpus",
      latitude: -6.1376,
      longitude: 106.8282,
      phone: null,
      whatsapp: "081218534516",
      website: null,
      instagram: "@bengkellaptop_",
      instagramFollowers: 4000,
      googleRating: 4.7,
      googleReviews: 400,
      tier: "B",
      tierReason: "Since 2004 (20+ years). All brands. Harco location for parts access.",
      surfaceConfirmed: false,
      surfaceNotes: "Long-established with parts access in Mangga Dua.",
      services: JSON.stringify(["All Brands", "LCD", "Battery", "Keyboard", "RAM", "SSD"]),
      lcdPriceMin: 500000,
      lcdPriceMax: 2000000,
      laborFee: 100000,
      warrantyDays: 30,
      operatingHours: JSON.stringify({ mon: "09:30-18:30", tue: "09:30-18:30", wed: "09:30-18:30", thu: "09:30-18:30", fri: "09:30-18:30", sat: "09:30-18:30", sun: "10:00-17:00" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: 21,
      specializations: JSON.stringify(["All Brands"]),
      certifications: null,
      dataSource: "Document 1,2,3",
    },

    // === TIER C ===
    {
      name: "Duo Laptop",
      address: "Harco Mangga Dua Plaza, Blok B Lt. Dasar No. 11",
      district: "Jakarta Pusat",
      area: "Mangga Dua",
      clusterId: "cluster-jakpus",
      latitude: -6.1378,
      longitude: 106.8286,
      phone: null,
      whatsapp: "081211680089",
      website: null,
      instagram: null,
      instagramFollowers: null,
      googleRating: 4.6,
      googleReviews: 200,
      tier: "C",
      tierReason: "Chip-level service specialist. Motherboard repair. Free consultation.",
      surfaceConfirmed: false,
      surfaceNotes: "Motherboard expertise may help with complex Surface issues.",
      services: JSON.stringify(["Motherboard", "Chip-level", "Reballing"]),
      lcdPriceMin: 500000,
      lcdPriceMax: 2000000,
      laborFee: null,
      warrantyDays: 30,
      operatingHours: JSON.stringify({ mon: "10:00-19:00", tue: "10:00-19:00", wed: "10:00-19:00", thu: "10:00-19:00", fri: "10:00-19:00", sat: "10:00-19:00", sun: "11:00-17:00" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: null,
      specializations: JSON.stringify(["Motherboard", "Chip-level"]),
      certifications: null,
      dataSource: "Document 1,3",
    },
    {
      name: "Laptop Heal",
      address: "Jl. Tegal Parang Selatan I No. 15, Mampang",
      district: "Jakarta Selatan",
      area: "Mampang",
      clusterId: "cluster-jaksel",
      latitude: -6.249,
      longitude: 106.834,
      phone: null,
      whatsapp: "085729116000",
      website: null,
      instagram: null,
      instagramFollowers: null,
      googleRating: 4.7,
      googleReviews: 80,
      tier: "C",
      tierReason: "Troubleshooting specialist. Budget-friendly. Konsultan komputer.",
      surfaceConfirmed: false,
      surfaceNotes: "Budget option for troubleshooting.",
      services: JSON.stringify(["Troubleshooting", "Budget Service"]),
      lcdPriceMin: 500000,
      lcdPriceMax: 1500000,
      laborFee: 50000,
      warrantyDays: 30,
      operatingHours: JSON.stringify({ mon: "09:00-18:00", tue: "09:00-18:00", wed: "09:00-18:00", thu: "09:00-18:00", fri: "09:00-18:00", sat: "09:00-17:00", sun: "closed" }),
      hasHomeService: false,
      hasPickupDelivery: false,
      yearsInBusiness: null,
      specializations: JSON.stringify(["Troubleshooting"]),
      certifications: null,
      dataSource: "Document 1",
    },
  ];

  for (const s of shops) {
    await prisma.shop.create({ data: s });
  }
  console.log(`Created ${shops.length} shops`);

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
