import { writeFileSync } from 'fs';

const H = (h) => JSON.stringify({ mon: h, tue: h, wed: h, thu: h, fri: h, sat: h, sun: h });
const HWD = (wd, sat, sun) => JSON.stringify({ mon: wd, tue: wd, wed: wd, thu: wd, fri: wd, sat, sun });

const clusters = [
  { id: "cluster-harco", name: "Harco Mangga Dua", type: "mall", address: "Jl. Mangga Dua Raya 18-19, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1377, longitude: 106.8284, avgVisitMinutes: 25, parkingInfo: "Parkir motor Rp 5.000, mobil Rp 10.000-15.000", bestVisitTime: "Weekday 10:00-14:00" },
  { id: "cluster-mangga-dua-mall", name: "Mangga Dua Mall/Square", type: "mall", address: "Jl. Mangga Dua Raya, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1380, longitude: 106.8290, avgVisitMinutes: 25, parkingInfo: "Basement parking available", bestVisitTime: "Weekday 11:00-15:00" },
  { id: "cluster-itc-fatmawati", name: "ITC Fatmawati", type: "mall", address: "Jl. RS Fatmawati No.39, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2916, longitude: 106.7991, avgVisitMinutes: 30, parkingInfo: "Parkir basement, motor Rp 3.000", bestVisitTime: "Any day 11:00-17:00" },
  { id: "cluster-itc-permata-hijau", name: "Grand ITC Permata Hijau", type: "mall", address: "Jl. Letjen Soepeno, Kebayoran Lama, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2275, longitude: 106.7820, avgVisitMinutes: 30, parkingInfo: "Parkir luas, motor Rp 3.000", bestVisitTime: "Weekday recommended" },
  { id: "cluster-mall-ambassador", name: "Mall Ambassador", type: "mall", address: "Jl. Prof. DR. Satrio, Kuningan, Jakarta Selatan", district: "Jakarta Selatan", latitude: -6.2270, longitude: 106.8310, avgVisitMinutes: 25, parkingInfo: "Basement parking", bestVisitTime: "Weekday 10:00-16:00" },
  { id: "cluster-roxy", name: "ITC Roxy Mas & Roxy Square", type: "mall", address: "Jl. KH. Hasyim Ashari, Grogol Petamburan, Jakarta Barat", district: "Jakarta Barat", latitude: -6.1883, longitude: 106.7897, avgVisitMinutes: 25, parkingInfo: "Multiple parking areas", bestVisitTime: "Weekday 10:00-15:00" },
  { id: "cluster-tanjung-duren", name: "Tanjung Duren Area", type: "area", address: "Jl. Tanjung Duren Raya, Jakarta Barat", district: "Jakarta Barat", latitude: -6.1698, longitude: 106.7823, avgVisitMinutes: 20, parkingInfo: "Street parking", bestVisitTime: "Any time during business hours" },
  { id: "cluster-kelapa-gading", name: "Kelapa Gading Area", type: "area", address: "Kelapa Gading, Jakarta Utara", district: "Jakarta Utara", latitude: -6.1580, longitude: 106.9050, avgVisitMinutes: 25, parkingInfo: "Mall or street parking", bestVisitTime: "Weekday to avoid traffic" },
  { id: "cluster-bcp", name: "Bekasi Cyber Park", type: "mall", address: "Jl. Ahmad Yani, Bekasi", district: "Bekasi", latitude: -6.2480, longitude: 107.0000, avgVisitMinutes: 25, parkingInfo: "Mall parking", bestVisitTime: "Weekday recommended" },
  { id: "cluster-cempaka-mas", name: "ITC Cempaka Mas", type: "mall", address: "Jl. Letjen Suprapto, Kemayoran, Jakarta Pusat", district: "Jakarta Pusat", latitude: -6.1660, longitude: 106.8740, avgVisitMinutes: 25, parkingInfo: "Large parking area", bestVisitTime: "Weekday 10:00-16:00" },
  { id: "cluster-wtc-serpong", name: "WTC Matahari Serpong", type: "mall", address: "Jl. Raya Serpong, Tangerang", district: "Tangerang/BSD", latitude: -6.2999, longitude: 106.6699, avgVisitMinutes: 25, parkingInfo: "Mall parking", bestVisitTime: "Weekday" },
  { id: "cluster-karawaci", name: "Supermal Karawaci", type: "mall", address: "Jl. Boulevard Diponegoro, Karawaci, Tangerang", district: "Tangerang/BSD", latitude: -6.2200, longitude: 106.6300, avgVisitMinutes: 25, parkingInfo: "Mall parking", bestVisitTime: "Any day" },
];

const tier1 = [
  { name: "Zapplerepair HQ", address: "Jl. Jembatan 3 Raya Ruko 11J, Jakarta Utara", district: "Jakarta Utara", area: "Pluit/Penjaringan", clusterId: null, latitude: -6.1291, longitude: 106.8447, phone: "0877-8885-5868", whatsapp: "6287788855868", website: "https://zapplerepair.com", instagram: "@zapplerepair", instagramFollowers: null, googleRating: 4.8, googleReviews: 500, tier: "1", tierReason: "SATU-SATUNYA Surface Specialist Indonesia. Original Surface parts, transparent pricing.", surfaceConfirmed: true, surfaceNotes: "LCD Rp 1.8-2.5jt, Touchpad Rp 500rb-1jt. Garansi 3-9 bulan.", services: JSON.stringify(["Surface LCD", "Surface Battery", "Surface Motherboard", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2500000, laborFee: 600000, warrantyDays: 270, operatingHours: HWD("08:00-20:00", "09:00-18:00", "09:00-18:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface", "Original Parts"]), certifications: null, dataSource: "User research" },
  { name: "Zapplerepair Roxy Square", address: "Roxy Square LG Blok B1 No.1, Jakarta Barat", district: "Jakarta Barat", area: "Grogol Petamburan", clusterId: "cluster-roxy", latitude: -6.1883, longitude: 106.7897, phone: "0877-8885-5868", whatsapp: "6287788855868", website: "https://zapplerepair.com", instagram: "@zapplerepair", instagramFollowers: null, googleRating: 4.8, googleReviews: 300, tier: "1", tierReason: "Same company as HQ, backup location. Surface + MacBook + Gaming.", surfaceConfirmed: true, surfaceNotes: "Same capabilities as HQ branch", services: JSON.stringify(["Surface LCD", "Surface Battery", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2500000, laborFee: 600000, warrantyDays: 270, operatingHours: HWD("08:00-20:00", "09:00-18:00", "09:00-18:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface", "MacBook", "Gaming"]), certifications: null, dataSource: "User research" },
  { name: "Zapplerepair Jakarta Selatan", address: "Jl. Mampang Prapatan Raya No.24C, Jakarta Selatan", district: "Jakarta Selatan", area: "Mampang Prapatan", clusterId: null, latitude: -6.2784, longitude: 106.8414, phone: "0877-8885-5868", whatsapp: "6287788855868", website: "https://zapplerepair.com", instagram: "@zapplerepair", instagramFollowers: null, googleRating: 4.8, googleReviews: 200, tier: "1", tierReason: "Closest Zapplerepair to start point in South Jakarta", surfaceConfirmed: true, surfaceNotes: "Same Surface service as HQ", services: JSON.stringify(["Surface LCD", "Surface Battery", "MacBook", "Gaming Laptop"]), lcdPriceMin: 1800000, lcdPriceMax: 2500000, laborFee: 600000, warrantyDays: 270, operatingHours: HWD("08:00-20:00", "closed", "closed"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: 10, specializations: JSON.stringify(["Microsoft Surface"]), certifications: null, dataSource: "User research" },
];

const tier2 = [
  { name: "Dr. Gadget ITC Fatmawati", address: "ITC Fatmawati, Jakarta Selatan", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2916, longitude: 106.7991, phone: null, whatsapp: null, website: null, instagram: "@docgadget_", instagramFollowers: 76000, googleRating: 4.7, googleReviews: 2000, tier: "2", tierReason: "Explicit Surface capability, BNSP certified, 8 branches, door-to-door service", surfaceConfirmed: true, surfaceNotes: "Multi-specialty including Microsoft Surface, Gaming Laptops, Nintendo", services: JSON.stringify(["Microsoft Surface", "Gaming Laptop", "Nintendo", "Apple"]), lcdPriceMin: 2500000, lcdPriceMax: 5000000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 8, specializations: JSON.stringify(["Surface", "Gaming Laptop", "Nintendo"]), certifications: "BNSP Certified", dataSource: "User research" },
  { name: "Pemmztechie Cilandak", address: "Jl. H. Nawi Raya No.9M, Cilandak, Jakarta Selatan", district: "Jakarta Selatan", area: "Cilandak", clusterId: null, latitude: -6.2891, longitude: 106.8095, phone: "0817-1717-3669", whatsapp: "6281717173669", website: "https://pemmztechie.id", instagram: "@pemmztechie.id", instagramFollowers: 6500, googleRating: 4.6, googleReviews: 600, tier: "2", tierReason: "Gaming specialist (ROG, Alienware, MSI, Razer), Dell authorized, 100K+ customers, 10+ years", surfaceConfirmed: false, surfaceNotes: "Premium gaming specialist may handle Surface", services: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI", "Razer"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:30-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Gaming Laptop", "Premium Laptop"]), certifications: "Dell Authorized", dataSource: "User research" },
  { name: "Pemmztechie HQ Tanjung Duren", address: "Jl. Tanjung Duren Raya 17A, Jakarta Barat", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1698, longitude: 106.7823, phone: "085-280-280-100", whatsapp: "6285280280100", website: "https://pemmztechie.id", instagram: "@pemmztechie.id", instagramFollowers: 6500, googleRating: 4.6, googleReviews: 400, tier: "2", tierReason: "HQ location, biggest inventory for gaming laptops", surfaceConfirmed: false, surfaceNotes: "Premium gaming expertise suggests capability", services: JSON.stringify(["Gaming Laptop", "ROG", "Alienware", "MSI"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: null, warrantyDays: 90, operatingHours: H("08:30-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Gaming Laptop"]), certifications: null, dataSource: "User research" },
  { name: "Zet Zet (Pemmz Group)", address: "Tanjung Duren Raya 17A Blok A11, Jakarta Barat", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1698, longitude: 106.7823, phone: "0857-7693-8953", whatsapp: "6285776938953", website: null, instagram: "@mr.zetzet", instagramFollowers: 4700, googleRating: 4.5, googleReviews: 300, tier: "2", tierReason: "Deep cleaning & optimization specialist, same building as Pemmz HQ, 10+ years", surfaceConfirmed: false, surfaceNotes: "Cleaning specialist for premium devices", services: JSON.stringify(["Deep Cleaning", "Thermal Paste", "Optimization"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: 200000, warrantyDays: 30, operatingHours: H("08:30-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Deep Cleaning", "Optimization"]), certifications: null, dataSource: "User research" },
  { name: "Pemmztechie BSD", address: "Sanctuary Collection AA2 No.50, BSD", district: "Tangerang/BSD", area: "BSD", clusterId: "cluster-wtc-serpong", latitude: -6.2999, longitude: 106.6699, phone: "085-280-280-100", whatsapp: "6285280280100", website: "https://pemmztechie.id", instagram: "@pemmztechie.id", instagramFollowers: 6500, googleRating: 4.6, googleReviews: 200, tier: "2", tierReason: "Serves BSD/Tangsel area, same capabilities as HQ", surfaceConfirmed: false, surfaceNotes: "BSD coverage", services: JSON.stringify(["Gaming Laptop", "Premium Laptop"]), lcdPriceMin: 1300000, lcdPriceMax: 3500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:30-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 10, specializations: JSON.stringify(["Gaming Laptop"]), certifications: null, dataSource: "User research" },
];

const tier3 = [
  { name: "Sodagar Komputer Ampera", address: "Jl. Ampera Raya No.4, Jakarta Selatan", district: "Jakarta Selatan", area: "Ampera", clusterId: null, latitude: -6.2646, longitude: 106.8153, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 3000, tier: "3", tierReason: "23 YEARS (since 2002), 10+ branches, Authorized Lenovo/HP/Asus/Acer/Axioo", surfaceConfirmed: false, surfaceNotes: "Highest review count - massive experience", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer", "Axioo"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Lenovo, HP, Asus, Acer Authorized", dataSource: "User research" },
  { name: "Sodagar Rawamangun", address: "Jl. Sunan Giri No.5, Rawamangun, Jakarta Timur", district: "Jakarta Timur", area: "Rawamangun", clusterId: null, latitude: -6.1930, longitude: 106.8790, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 500, tier: "3", tierReason: "Same Sodagar network - authorized service", surfaceConfirmed: false, surfaceNotes: "East Jakarta coverage", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Authorized Service Partner", dataSource: "User research" },
  { name: "Sodagar Jatiwaringin", address: "Jl. Raya Jatiwaringin 11C, Jakarta Timur", district: "Jakarta Timur", area: "Jatiwaringin", clusterId: null, latitude: -6.2600, longitude: 106.9100, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 300, tier: "3", tierReason: "Sodagar branch for East Jakarta", surfaceConfirmed: false, surfaceNotes: "Same authorized services", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Authorized Service Partner", dataSource: "User research" },
  { name: "Sodagar Pondok Kopi", address: "Ruko Robusta Raya R2/6C, Pondok Kopi", district: "Jakarta Timur", area: "Pondok Kopi", clusterId: null, latitude: -6.2200, longitude: 106.9300, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 200, tier: "3", tierReason: "Sodagar network coverage", surfaceConfirmed: false, surfaceNotes: "East Jakarta", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Authorized Service Partner", dataSource: "User research" },
  { name: "Sodagar Pekayon Bekasi", address: "Jl. Raya Pekayon No.1, Bekasi", district: "Bekasi", area: "Pekayon", clusterId: null, latitude: -6.2800, longitude: 106.9700, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 200, tier: "3", tierReason: "Sodagar Bekasi coverage", surfaceConfirmed: false, surfaceNotes: "Bekasi area", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Authorized Service Partner", dataSource: "User research" },
  { name: "Sodagar Cikarang", address: "Jl. Serang-Cibarusah No.69, Cikarang", district: "Bekasi", area: "Cikarang", clusterId: null, latitude: -6.3100, longitude: 107.1500, phone: "0821-2379-0480", whatsapp: "6282123790480", website: "https://sodagarkomputer.com", instagram: "@sodagarkomputer", instagramFollowers: 33000, googleRating: 4.6, googleReviews: 150, tier: "3", tierReason: "Sodagar Cikarang coverage", surfaceConfirmed: false, surfaceNotes: "Industrial area coverage", services: JSON.stringify(["Lenovo", "HP", "Asus", "Acer"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("08:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 23, specializations: JSON.stringify(["Authorized Brand Service"]), certifications: "Authorized Service Partner", dataSource: "User research" },
  { name: "ASUS Service Center Harco", address: "Harco Mangga Dua, Jl. Mangga Dua Raya 18-19", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1377, longitude: 106.8284, phone: "1500-128", whatsapp: null, website: "https://asus.com", instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 400, tier: "3", tierReason: "OFFICIAL ASUS/ROG - premium gaming expertise", surfaceConfirmed: false, surfaceNotes: "ROG expertise = complex device capability", services: JSON.stringify(["ASUS", "ROG", "Official Parts"]), lcdPriceMin: 1500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["ASUS", "ROG"]), certifications: "ASUS Official", dataSource: "User research" },
  { name: "ASUS Service Center Mangga Dua Square", address: "Mangga Dua Square Lt.1 BP044", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1380, longitude: 106.8290, phone: "1500-128", whatsapp: null, website: "https://asus.com", instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 300, tier: "3", tierReason: "OFFICIAL ASUS/ROG", surfaceConfirmed: false, surfaceNotes: "Second official ASUS location", services: JSON.stringify(["ASUS", "ROG", "Official Parts"]), lcdPriceMin: 1500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["ASUS", "ROG"]), certifications: "ASUS Official", dataSource: "User research" },
  { name: "Acer Service Center Fatmawati", address: "ITC Fatmawati No.7", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2916, longitude: 106.7991, phone: "1500-155", whatsapp: null, website: "https://acer.com", instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 250, tier: "3", tierReason: "OFFICIAL Acer Service Center", surfaceConfirmed: false, surfaceNotes: "Official Acer service", services: JSON.stringify(["Acer", "Official Parts"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Acer"]), certifications: "Acer Official", dataSource: "User research" },
  { name: "Acer Service Center Mangga Dua", address: "Mangga Dua Square Blok H 28-29", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1380, longitude: 106.8290, phone: "1500-155", whatsapp: null, website: "https://acer.com", instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 200, tier: "3", tierReason: "OFFICIAL Acer", surfaceConfirmed: false, surfaceNotes: "Mangga Dua location", services: JSON.stringify(["Acer", "Official Parts"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 90, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Acer"]), certifications: "Acer Official", dataSource: "User research" },
  { name: "HP Service Center Kasablanka", address: "Prudential Center Lt.5, Kasablanka", district: "Jakarta Selatan", area: "Kasablanka", clusterId: null, latitude: -6.2230, longitude: 106.8430, phone: "021-2975-9210", whatsapp: null, website: "https://hp.com", instagram: null, instagramFollowers: null, googleRating: 4.3, googleReviews: 200, tier: "3", tierReason: "OFFICIAL HP - Spectre, Envy, Omen expertise", surfaceConfirmed: false, surfaceNotes: "Premium ultrabook expertise", services: JSON.stringify(["HP Spectre", "HP Envy", "HP Omen", "Official Parts"]), lcdPriceMin: 1500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: HWD("09:00-17:00", "closed", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["HP Premium"]), certifications: "HP Official", dataSource: "User research" },
  { name: "Dell Service Center Fatmawati", address: "Ruko D'Best, RS Fatmawati 15/E43", district: "Jakarta Selatan", area: "Fatmawati", clusterId: null, latitude: -6.2900, longitude: 106.7980, phone: "021-7591-4343", whatsapp: null, website: "https://dell.com", instagram: null, instagramFollowers: null, googleRating: 4.3, googleReviews: 180, tier: "3", tierReason: "OFFICIAL Dell - XPS/Precision expertise", surfaceConfirmed: false, surfaceNotes: "Premium Windows laptop expertise", services: JSON.stringify(["Dell XPS", "Dell Precision", "Official Parts"]), lcdPriceMin: 1500000, lcdPriceMax: 4000000, laborFee: null, warrantyDays: 90, operatingHours: HWD("09:00-17:00", "closed", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Dell Premium"]), certifications: "Dell Official", dataSource: "User research" },
];

const tier4 = [
  { name: "Teknisigo Tebet", address: "Jl. Tebet Timur Dalam Raya, Jakarta Selatan", district: "Jakarta Selatan", area: "Tebet", clusterId: null, latitude: -6.2386, longitude: 106.8611, phone: null, whatsapp: null, website: "https://teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 1500, tier: "4", tierReason: "18+ years, viral TikTok, 244K followers - HIGHEST social presence", surfaceConfirmed: false, surfaceNotes: "Real-time tracking, massive volume", services: JSON.stringify(["All Brands", "LCD", "Battery", "SSD"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: H("09:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["High Volume", "Home Service"]), certifications: null, dataSource: "User research" },
  { name: "Teknisigo Fatmawati", address: "Jl. Fatmawati Raya No.14", district: "Jakarta Selatan", area: "Fatmawati", clusterId: null, latitude: -6.2900, longitude: 106.7990, phone: null, whatsapp: null, website: "https://teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 800, tier: "4", tierReason: "Teknisigo branch near ITC Fatmawati", surfaceConfirmed: false, surfaceNotes: "Same capabilities", services: JSON.stringify(["All Brands", "LCD", "Battery"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["High Volume"]), certifications: null, dataSource: "User research" },
  { name: "Teknisigo Harco Mangga Dua", address: "Harco Mangga Dua", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1377, longitude: 106.8284, phone: null, whatsapp: null, website: "https://teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 600, tier: "4", tierReason: "Teknisigo in parts hub", surfaceConfirmed: false, surfaceNotes: "Access to wholesale parts", services: JSON.stringify(["All Brands", "LCD", "Battery"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["High Volume"]), certifications: null, dataSource: "User research" },
  { name: "Teknisigo Tanjung Duren", address: "Jl. Tanjung Duren Raya 108B", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1700, longitude: 106.7830, phone: null, whatsapp: null, website: "https://teknisigo.com", instagram: "@teknisigo_id", instagramFollowers: 244000, googleRating: 4.7, googleReviews: 400, tier: "4", tierReason: "West Jakarta Teknisigo", surfaceConfirmed: false, surfaceNotes: "Same network", services: JSON.stringify(["All Brands", "LCD", "Battery"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: 150000, warrantyDays: 90, operatingHours: H("10:00-20:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: 18, specializations: JSON.stringify(["High Volume"]), certifications: null, dataSource: "User research" },
  { name: "Rimas Laptop Jakarta", address: "Tanjung Duren (opposite Mall Taman Anggrek)", district: "Jakarta Barat", area: "Tanjung Duren", clusterId: "cluster-tanjung-duren", latitude: -6.1760, longitude: 106.7900, phone: "7635-989-777", whatsapp: null, website: null, instagram: "@rimaslaptopjakarta", instagramFollowers: 68000, googleRating: 4.7, googleReviews: 3000, tier: "4", tierReason: "68K followers, home service, buy/sell = parts access", surfaceConfirmed: false, surfaceNotes: "Extended hours until 21:00", services: JSON.stringify(["All Brands", "Buy/Sell", "Trade-in"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-21:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Buy/Sell", "Home Service"]), certifications: null, dataSource: "User research" },
  { name: "Rimas Laptop Kelapa Gading", address: "Opposite MKG, Kelapa Gading", district: "Jakarta Utara", area: "Kelapa Gading", clusterId: "cluster-kelapa-gading", latitude: -6.1580, longitude: 106.9050, phone: "7635-905-905", whatsapp: null, website: null, instagram: "@rimaslaptop.kelapagading", instagramFollowers: 64000, googleRating: 4.8, googleReviews: 600, tier: "4", tierReason: "64K followers, Kelapa Gading premium area", surfaceConfirmed: false, surfaceNotes: "North Jakarta coverage", services: JSON.stringify(["All Brands", "LCD", "Home Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-21:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Home Service"]), certifications: null, dataSource: "User research" },
  { name: "Rimas Laptop Cibubur", address: "Opposite Ciputra Mall Cibubur", district: "Jakarta Timur", area: "Cibubur", clusterId: null, latitude: -6.3700, longitude: 106.8800, phone: "7635-7777-53", whatsapp: null, website: null, instagram: "@rimaslaptopcibubur", instagramFollowers: 84000, googleRating: 4.7, googleReviews: 500, tier: "4", tierReason: "84K followers - HIGHEST Rimas branch", surfaceConfirmed: false, surfaceNotes: "Cibubur area coverage", services: JSON.stringify(["All Brands", "LCD", "Home Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-21:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Home Service"]), certifications: null, dataSource: "User research" },
  { name: "Rimas Laptop Bintaro", address: "Opposite STAN, Bintaro", district: "Tangerang/BSD", area: "Bintaro", clusterId: null, latitude: -6.2800, longitude: 106.7200, phone: "7635-765-666", whatsapp: null, website: null, instagram: "@rimaslaptopbintaro", instagramFollowers: 51000, googleRating: 4.7, googleReviews: 400, tier: "4", tierReason: "51K followers, Bintaro coverage", surfaceConfirmed: false, surfaceNotes: "Tangsel area", services: JSON.stringify(["All Brands", "LCD", "Home Service"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-21:00"), hasHomeService: true, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Home Service"]), certifications: null, dataSource: "User research" },
  { name: "Valdis Computer Kelapa Gading", address: "Jl. Boulevard Raya Blok LC7 No.12, Kelapa Gading", district: "Jakarta Utara", area: "Kelapa Gading", clusterId: "cluster-kelapa-gading", latitude: -6.1585, longitude: 106.9045, phone: "+6221-458-50-242", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.8, googleReviews: 400, tier: "4", tierReason: "Since 2001 (24 YEARS), premium area service", surfaceConfirmed: false, surfaceNotes: "Long-established premium service", services: JSON.stringify(["All Brands", "Gaming"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-18:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 24, specializations: JSON.stringify(["Gaming", "Premium"]), certifications: null, dataSource: "User research" },
];

const tier5 = [
  { name: "iRepair Computer ITC Fatmawati", address: "ITC Fatmawati LD-148", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2920, longitude: 106.7968, phone: "08176411234", whatsapp: "6281764112234", website: null, instagram: "@servicelaptop_jakarta", instagramFollowers: 3000, googleRating: 5.0, googleReviews: 80, tier: "5", tierReason: "PERFECT 5.0/5 rating", surfaceConfirmed: false, surfaceNotes: "All brands capable", services: JSON.stringify(["All Brands", "MacBook", "VGA Chipset"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Easy Computer", address: "ITC Fatmawati Lt.3-1", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2920, longitude: 106.7970, phone: "021-7237347", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 60, tier: "5", tierReason: "ITC Fatmawati cluster", surfaceConfirmed: false, surfaceNotes: "General service", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "DIGITALCOM", address: "ITC Fatmawati Lt.3", district: "Jakarta Selatan", area: "Fatmawati", clusterId: "cluster-itc-fatmawati", latitude: -6.2920, longitude: 106.7972, phone: "0878-2649-7710", whatsapp: "6287826497710", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 50, tier: "5", tierReason: "ITC Fatmawati cluster", surfaceConfirmed: false, surfaceNotes: "General service", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "R Komputer", address: "ITC Permata Hijau Lt.3 D2.03", district: "Jakarta Selatan", area: "Kebayoran Lama", clusterId: "cluster-itc-permata-hijau", latitude: -6.2275, longitude: 106.7820, phone: "0812-9250-2305", whatsapp: "6281292502305", website: null, instagram: null, instagramFollowers: null, googleRating: 5.0, googleReviews: 70, tier: "5", tierReason: "PERFECT 5.0/5 - Since 2011 (14 years), LCD expert", surfaceConfirmed: false, surfaceNotes: "Fast service, honest technicians", services: JSON.stringify(["All Brands", "LCD Expert"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-20:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 14, specializations: JSON.stringify(["LCD Expert"]), certifications: null, dataSource: "User research" },
  { name: "Arisa Computer", address: "Mall Ambassador Lt.3-45, Kuningan", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2270, longitude: 106.8310, phone: "0811-1041-840", whatsapp: "6281110418400", website: null, instagram: "@arisacomp", instagramFollowers: 10000, googleRating: 4.8, googleReviews: 300, tier: "5", tierReason: "Free pickup/delivery, Lenovo specialist, business district", surfaceConfirmed: false, surfaceNotes: "Premium service level", services: JSON.stringify(["Lenovo", "All Brands", "Premium Service"]), lcdPriceMin: 1500000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["Lenovo", "Premium"]), certifications: null, dataSource: "User research" },
  { name: "Dokter Laptop", address: "Mall Ambassador Lt.3-47", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2268, longitude: 106.8308, phone: "0812-8101-0197", whatsapp: "6281281010197", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 350, tier: "5", tierReason: "Detailed diagnosis, strategic location", surfaceConfirmed: false, surfaceNotes: "Business district location", services: JSON.stringify(["All Brands", "Detailed Diagnosis"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-19:00", "10:00-17:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "ZIRO Laptop", address: "Mall Ambassador Lt.3 Jmb.2-47", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2269, longitude: 106.8309, phone: "0813-6170-6175", whatsapp: "6281361706175", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 150, tier: "5", tierReason: "Ambassador cluster, good rating", surfaceConfirmed: false, surfaceNotes: "Mall location", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Unicomputer", address: "Mall Ambassador Lt.2 Jmb.2-56", district: "Jakarta Selatan", area: "Kuningan", clusterId: "cluster-mall-ambassador", latitude: -6.2267, longitude: 106.8307, phone: "0811-2626-146", whatsapp: "6281126261466", website: null, instagram: "@unicomputer.id", instagramFollowers: null, googleRating: 4.6, googleReviews: 100, tier: "5", tierReason: "Corporate service available", surfaceConfirmed: false, surfaceNotes: "On-site corporate service", services: JSON.stringify(["MacBook", "PC", "Corporate"]), lcdPriceMin: 1000000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-19:00", "10:00-19:00", "closed"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Corporate Service"]), certifications: null, dataSource: "User research" },
];

const tier6 = [
  { name: "Bengkel Laptop Harco", address: "Harco Mangga Dua Lt.Dasar No.91", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1376, longitude: 106.8282, phone: "0812-1853-4516", whatsapp: "6281218534516", website: null, instagram: "@bengkellaptop_", instagramFollowers: 4000, googleRating: 4.6, googleReviews: 400, tier: "6", tierReason: "Since 2004 (21 YEARS) - longest in Mangga Dua", surfaceConfirmed: false, surfaceNotes: "Long-established with parts access", services: JSON.stringify(["All Brands", "LCD", "Battery", "RAM", "SSD"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: 100000, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 21, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Duo Laptop Harco", address: "Harco Mangga Dua Lt.Dasar", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1378, longitude: 106.8286, phone: "0812-1168-0089", whatsapp: "6281211680089", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 200, tier: "6", tierReason: "Motherboard repair, chip-level, reballing specialist", surfaceConfirmed: false, surfaceNotes: "Component-level expertise", services: JSON.stringify(["Motherboard", "Chip-level", "Reballing"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Chip-level", "Motherboard"]), certifications: null, dataSource: "User research" },
  { name: "Computer Solution Harco", address: "Harco Mangga Dua", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1375, longitude: 106.8280, phone: "021-9258-3354", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 150, tier: "6", tierReason: "Mainboard/chip level specialist", surfaceConfirmed: false, surfaceNotes: "Complex repair capable", services: JSON.stringify(["Mainboard", "Chip-level"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Chip-level"]), certifications: null, dataSource: "User research" },
  { name: "JayaSakti Notebook", address: "Harco Mangga Dua Lt.1 A-94", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1374, longitude: 106.8278, phone: "021-6120630", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 150, tier: "6", tierReason: "Parts replacement specialist", surfaceConfirmed: false, surfaceNotes: "In parts hub", services: JSON.stringify(["All Brands", "Parts"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-18:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "ServiceMac.id", address: "Mangga Dua Mall LD-20A", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1381, longitude: 106.8292, phone: "08170917411", whatsapp: "628170917411", website: null, instagram: "@servicemac.id", instagramFollowers: null, googleRating: 4.9, googleReviews: 200, tier: "6", tierReason: "4.9/5 rating, also handles Windows laptops", surfaceConfirmed: false, surfaceNotes: "Premium service quality", services: JSON.stringify(["MacBook", "Windows Laptop"]), lcdPriceMin: 1000000, lcdPriceMax: 3000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["MacBook", "Windows"]), certifications: null, dataSource: "User research" },
  { name: "FIXPRO Service", address: "Mall Mangga Dua Lt.5 K-4", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1382, longitude: 106.8294, phone: "0812-1296-2827", whatsapp: "6281212962827", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 100, tier: "6", tierReason: "Hardware specialist, budget pricing", surfaceConfirmed: false, surfaceNotes: "Budget option", services: JSON.stringify(["Hardware", "All Brands"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: 50000, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Hardware"]), certifications: null, dataSource: "User research" },
  { name: "M2M Notebook", address: "Mangga Dua Mall Lt.4 A-73A", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1383, longitude: 106.8295, phone: "0856-8076-281", whatsapp: "6285680762811", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 80, tier: "6", tierReason: "Mangga Dua Mall cluster", surfaceConfirmed: false, surfaceNotes: "General service", services: JSON.stringify(["All Brands"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Hariez Central Service", address: "Mall Mangga Dua Lt.5 C59-60", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1384, longitude: 106.8296, phone: "0813-1300-6700", whatsapp: "6281313006700", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 100, tier: "6", tierReason: "'Anti gagal' reputation - honest diagnostics", surfaceConfirmed: false, surfaceNotes: "Known for honest assessments", services: JSON.stringify(["All Brands", "Honest Diagnosis"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Honest Diagnosis"]), certifications: null, dataSource: "User research" },
  { name: "Dell Store by Eleno", address: "Mall Mangga Dua Lt.1-38", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-mangga-dua-mall", latitude: -6.1385, longitude: 106.8297, phone: "021-6220-2908", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 100, tier: "6", tierReason: "Dell focus in Mangga Dua", surfaceConfirmed: false, surfaceNotes: "Dell expertise", services: JSON.stringify(["Dell"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Dell"]), certifications: null, dataSource: "User research" },
  { name: "Notname Computer", address: "Harco Mangga Dua area", district: "Jakarta Pusat", area: "Mangga Dua", clusterId: "cluster-harco", latitude: -6.1377, longitude: 106.8283, phone: "0896-6172-5376", whatsapp: "6289661725376", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 80, tier: "6", tierReason: "Data recovery, IC power specialist", surfaceConfirmed: false, surfaceNotes: "Specialized services", services: JSON.stringify(["Data Recovery", "IC Power"]), lcdPriceMin: 500000, lcdPriceMax: 2000000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Data Recovery", "IC Power"]), certifications: null, dataSource: "User research" },
  { name: "M-CARE Lenovo (Official)", address: "ITC Cempaka Mas + Roxy Square", district: "Jakarta Pusat", area: "Cempaka Mas", clusterId: "cluster-cempaka-mas", latitude: -6.1660, longitude: 106.8740, phone: "021-2148-0901", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.4, googleReviews: 200, tier: "6", tierReason: "OFFICIAL Lenovo service", surfaceConfirmed: false, surfaceNotes: "Official Lenovo", services: JSON.stringify(["Lenovo", "Official Parts"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 90, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Lenovo"]), certifications: "Lenovo Official", dataSource: "User research" },
  { name: "Stabiliskom (Home Service Only)", address: "Home service - Alam Sutera/Gading Serpong", district: "Tangerang/BSD", area: "Mobile Service", clusterId: null, latitude: -6.2200, longitude: 106.6500, phone: "0812-9488-3042", whatsapp: "6281294883042", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 100, tier: "6", tierReason: "BIOS/motherboard specialist, 2-hour guarantee, no fix = no charge", surfaceConfirmed: false, surfaceNotes: "Home service only - no walk-ins", services: JSON.stringify(["BIOS", "Motherboard", "Home Service Only"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: null, warrantyDays: 30, operatingHours: H("By appointment"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["BIOS", "Motherboard"]), certifications: null, dataSource: "User research" },
];

const tier7 = [
  { name: "Quick Service BCP", address: "Mall BCP Lt.1 B2-17, Bekasi Selatan", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2480, longitude: 107.0000, phone: "0851-0777-1771", whatsapp: "6285107771771", website: null, instagram: "@quick_service_laptop", instagramFollowers: null, googleRating: 4.9, googleReviews: 469, tier: "7", tierReason: "BEST IN BEKASI - 4.9/5 with 469 reviews", surfaceConfirmed: false, surfaceNotes: "Highest Bekasi rating with volume", services: JSON.stringify(["All Brands", "LCD", "Keyboard", "Battery", "Hinge", "SSD"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Sentral Service BCP", address: "BCP Lt.1 A11-22, Bekasi", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2482, longitude: 107.0002, phone: "0819-7777-1800", whatsapp: "6281977771800", website: null, instagram: "@sentralservice_bcp", instagramFollowers: 1400, googleRating: 4.6, googleReviews: 200, tier: "7", tierReason: "ROG specialist, HP partner", surfaceConfirmed: false, surfaceNotes: "Official partner status", services: JSON.stringify(["HP", "ROG", "All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["HP", "ROG"]), certifications: "HP Official Partner", dataSource: "User research" },
  { name: "Don Duan Computer BCP", address: "BCP Blok A11, Bekasi", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2481, longitude: 107.0003, phone: "0821-1091-9414", whatsapp: "6282110919414", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 100, tier: "7", tierReason: "BCP cluster, parts in stock", surfaceConfirmed: false, surfaceNotes: "Parts availability", services: JSON.stringify(["All Brands", "Parts"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Juniar Computer BCP", address: "BCP Lt.1 A3-8, Bekasi", district: "Bekasi", area: "Bekasi Selatan", clusterId: "cluster-bcp", latitude: -6.2478, longitude: 107.0001, phone: "0822-1624-2081", whatsapp: "6282216242081", website: null, instagram: null, instagramFollowers: null, googleRating: 4.7, googleReviews: 150, tier: "7", tierReason: "General + projector, good rating", surfaceConfirmed: false, surfaceNotes: "Parts in stock", services: JSON.stringify(["All Brands", "Projector"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("10:00-20:00", "10:00-21:00", "10:00-21:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Chintya Computer", address: "Jl. Cut Mutia 11, Bekasi Timur", district: "Bekasi", area: "Bekasi Timur", clusterId: null, latitude: -6.2400, longitude: 107.0150, phone: "0812-8287-2518", whatsapp: "6281282872518", website: null, instagram: null, instagramFollowers: null, googleRating: 5.0, googleReviews: 80, tier: "7", tierReason: "PERFECT 5.0/5 - Budget-friendly with perfect rating", surfaceConfirmed: false, surfaceNotes: "Best value in Bekasi", services: JSON.stringify(["All Brands", "Budget Service"]), lcdPriceMin: 500000, lcdPriceMax: 1500000, laborFee: 50000, warrantyDays: 30, operatingHours: HWD("09:00-19:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Budget Service"]), certifications: null, dataSource: "User research" },
  { name: "Success Computer Cibubur", address: "Ruko Citra Gran 23, Cibubur", district: "Jakarta Timur", area: "Cibubur", clusterId: null, latitude: -6.3650, longitude: 106.8850, phone: "021-845-2024", whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 100, tier: "7", tierReason: "Free pickup 5km radius", surfaceConfirmed: false, surfaceNotes: "Cibubur coverage", services: JSON.stringify(["All Brands", "Free Pickup"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: true, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Giant Computer Cibubur", address: "Jl. Caman Raya No.1, Jatibening", district: "Bekasi", area: "Jatibening", clusterId: null, latitude: -6.2600, longitude: 106.9400, phone: "0857-8086-4001", whatsapp: "6285780864001", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 80, tier: "7", tierReason: "Part of Teknisigo network", surfaceConfirmed: false, surfaceNotes: "Teknisigo affiliate", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Berkah Komputer Cikarang", address: "Gramapuri Persada G2/46, Cikarang", district: "Bekasi", area: "Cikarang", clusterId: null, latitude: -6.3100, longitude: 107.1400, phone: "0813-8579-3811", whatsapp: "6281385793811", website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 60, tier: "7", tierReason: "Corporate contracts available", surfaceConfirmed: false, surfaceNotes: "Industrial area service", services: JSON.stringify(["All Brands", "Corporate"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: HWD("09:00-18:00", "09:00-17:00", "closed"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["Corporate"]), certifications: null, dataSource: "User research" },
];

const tier8 = [
  { name: "LightTech Computer", address: "WTC Matahari Serpong + 3 locations", district: "Tangerang/BSD", area: "Serpong", clusterId: "cluster-wtc-serpong", latitude: -6.2999, longitude: 106.6699, phone: "0838-9916-1681", whatsapp: "6283899161681", website: null, instagram: null, instagramFollowers: null, googleRating: 5.0, googleReviews: 100, tier: "8", tierReason: "PERFECT 5.0/5 - Since 2011 (14 years), 4 locations", surfaceConfirmed: false, surfaceNotes: "Best in Tangerang area", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: 14, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "iRepair Computer Karawaci", address: "e-Center Supermal Karawaci FF H2/3A", district: "Tangerang/BSD", area: "Karawaci", clusterId: "cluster-karawaci", latitude: -6.2200, longitude: 106.6300, phone: "0817-641-1234", whatsapp: "6281764112234", website: null, instagram: "@servicelaptop_tangerang", instagramFollowers: 3000, googleRating: 5.0, googleReviews: 90, tier: "8", tierReason: "PERFECT 5.0/5 - Same company as ITC Fatmawati", surfaceConfirmed: false, surfaceNotes: "Same quality as Jakarta branch", services: JSON.stringify(["All Brands", "MacBook"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-20:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Irepair ABA Pamulang", address: "Ruko Villa Dago AD/02, Pamulang", district: "Tangerang/BSD", area: "Pamulang", clusterId: null, latitude: -6.3400, longitude: 106.7300, phone: null, whatsapp: null, website: null, instagram: null, instagramFollowers: null, googleRating: 4.5, googleReviews: 60, tier: "8", tierReason: "Pamulang area coverage", surfaceConfirmed: false, surfaceNotes: "South Tangerang", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("10:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Voltera Computer", address: "Jl. Kubinka 19, Gading Serpong", district: "Tangerang/BSD", area: "Gading Serpong", clusterId: null, latitude: -6.2400, longitude: 106.6200, phone: "0812-8679-8588", whatsapp: "6281286798588", website: null, instagram: "@volteracomputer", instagramFollowers: null, googleRating: 4.7, googleReviews: 80, tier: "8", tierReason: "Gading Serpong area", surfaceConfirmed: false, surfaceNotes: "Premium area service", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Corel Computer", address: "Multiple Tangsel locations (Ciputat, Bintaro)", district: "Tangerang/BSD", area: "Ciputat", clusterId: null, latitude: -6.3100, longitude: 106.7400, phone: "0821-2520-3477", whatsapp: "6282125203477", website: null, instagram: "@corelcomputer", instagramFollowers: null, googleRating: 4.5, googleReviews: 70, tier: "8", tierReason: "Multiple Tangsel locations", surfaceConfirmed: false, surfaceNotes: "Tangsel coverage", services: JSON.stringify(["All Brands"]), lcdPriceMin: 800000, lcdPriceMax: 2500000, laborFee: null, warrantyDays: 30, operatingHours: H("09:00-19:00"), hasHomeService: false, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["All Brands"]), certifications: null, dataSource: "User research" },
  { name: "Ferocious Digital", address: "Tangerang Selatan area", district: "Tangerang/BSD", area: "Tangerang Selatan", clusterId: null, latitude: -6.2900, longitude: 106.7100, phone: "0811-1221-281", whatsapp: "6281112212811", website: null, instagram: null, instagramFollowers: null, googleRating: 4.6, googleReviews: 50, tier: "8", tierReason: "24-HOUR EMERGENCY SERVICE", surfaceConfirmed: false, surfaceNotes: "Only 24-hour option", services: JSON.stringify(["All Brands", "24-hour Emergency"]), lcdPriceMin: null, lcdPriceMax: null, laborFee: null, warrantyDays: 30, operatingHours: H("24 Hours"), hasHomeService: true, hasPickupDelivery: false, yearsInBusiness: null, specializations: JSON.stringify(["24-hour Service"]), certifications: null, dataSource: "User research" },
];

const allShops = [...tier1, ...tier2, ...tier3, ...tier4, ...tier5, ...tier6, ...tier7, ...tier8];

// Add IDs
const shopsWithIds = allShops.map((shop, index) => ({
  id: `shop-${String(index + 1).padStart(3, '0')}`,
  ...shop,
  lastVerified: null,
  notes: null,
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
}));

const clustersWithTimestamps = clusters.map(c => ({
  ...c,
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2024-01-01T00:00:00.000Z",
}));

writeFileSync('/home/user/spam/src/data/shops.json', JSON.stringify(shopsWithIds, null, 2));
writeFileSync('/home/user/spam/src/data/clusters.json', JSON.stringify(clustersWithTimestamps, null, 2));

console.log(`Generated ${shopsWithIds.length} shops and ${clustersWithTimestamps.length} clusters`);
