name: Mirror to GitLab
on:
  push:
    branches: ["**"]
  delete:
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/subkhanibnuaji1/${{ github.event.repository.name }}.git || true
          git push gitlab --all --force
          git push gitlab --tags --force